# -*- coding: utf-8 -*-
"""validadorDNI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F-U_8Bd1I1Q3oleKGPwDk47js9hihEQ7

**VALIDADOR DE DNI**
"""

JorgeLista = {
'Daniel' : 34445445,
'Luciana' : 34449442,
'Ricardo' : 34354345,
'Leonel' : 32544532,
'Pepe' : 32443897,
'Rogelio' : 29992192,
'Coco' : 34234598,
'Melisa' : 36228190,
'Lisa' : 29001921,
'Homero' : 33238591,
'Eduardo' : 34698124,
'Santos' : 34213514,
'Cossety' : 34556442,
'Carla' : 34214554,
'Lapicito' : 34445245
}

ppr = 0
res = 0 

for (k) in iter(JorgeLista.items()):  
  ppr = ppr + 1

while True: 
  try: 
    dni = int(input("Ingrese el numero de tu DNI"))
    for (k, v) in iter(JorgeLista.items()):
      if v == dni and ppr != 0:
        ppr = ppr - 1
        print("es", (k), ("dejale entrar"))
        print("restan", (ppr), "invitados")
        break
    if ppr <= 0:
      print("ya entraron todos!")
    if v != dni:
      print("Usted no esta en la lista")
  except:
    print("no es un numero de DNI")